name: 'Docker build an push image'
description: 'Builds and pushed docker image'
inputs:
  image-name:
    description: 'Name of docker image'
    required: true
  version:  # id of input
    description: 'Version of docker image'
    required: true
  context:  # id of input
    description: 'Context of docker build'
    required: true
  architecture:
    description: 'Architecture of docker image'
    default: 'amd64'
  major-version:
    description: 'Major version of docker image'
  build-args:
    description: 'Build args of docker build'
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: true
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build Docker Image
      if: ${{ inputs.major-version == '' }}
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        platforms: linux/${{ inputs.architecture }}
        tags: ${{ inputs.image-name }}:${{ inputs.version }}
        build-args: ${{ inputs.build-args }}
        push: true

    - name: Build Docker Image
      if: ${{ inputs.major-version != '' }}
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        platforms: linux/${{ inputs.architecture }}
        tags: |
          ${{ inputs.image-name }}:${{ inputs.version }}
          ${{ inputs.image-name }}:${{ inputs.major-version }}
          ${{ inputs.image-name }}:latest
        build-args: ${{ inputs.build-args }}
        push: true

